# Generated by Django 3.2.17 on 2023-02-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costs', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('start_end', models.DateTimeField()),
            ],
        ),
    ]
